FROM %%BASE%%:%%BASE_TAG%%

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update -qq \
    && apt-get install -y -qq --no-install-recommends \
       binutils \
       module-init-tools \
    && /bin/bash -c "wget -q -O /tmp/nvidia-driver.run\
 http://us.download.nvidia.com/XFree86/Linux-x86_64/%%NVIDIA_VERSION%%/NVIDIA-Linux-x86_64-%%NVIDIA_VERSION%%.run &&\
 sh /tmp/nvidia-driver.run -a -N --ui=none --no-kernel-module &&\
 rm /tmp/nvidia-driver.run" \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
